---
- name: Deploy to EKS Cluster
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Apply Kubernetes Manifests (Deployment & Service)
      kubernetes.core.k8s:
        state: absent
        src: "{{ item }}"
        namespace: default
      with_fileglob:
        - "/home/ec2-user/jenkins-data/workspace/bookmyshow/k8s/*.yaml"
